Dockerfile.%: .pipeline/blubber.yaml
	echo "# Generated by Blubber from $^" > $@
	curl -sH 'content-type: application/yaml' --data-binary @$^ \
	https://blubberoid.wikimedia.org/v1/$(*F) >> $@

.devimage: Dockerfile.dev
	docker build . -f Dockerfile.dev -t shellbox-dev:local
	touch .devimage

.testimage: Dockerfile.test
	docker build . -f Dockerfile.test -t shellbox-test:local
	touch .testimage

test: .testimage
	docker run -v $(CURDIR)/src:/srv/app/src -v $(CURDIR)/tests:/srv/app/tests --rm shellbox-test:local

run: Dockerfile.dev
	docker-compose up

rebuild: Dockerfile.dev
	docker-compose up --build

clean:
	-rm Dockerfile*
	-rm .testimage .devimage
	-docker-compose rm -fsv

.PHONY: clean run test
