pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: test-php73
      - name: test-php74
  publish:
    blubberfile: blubber.yaml
    stages:
      # Plain Shellbox with just PHP for RPC
      - name: php-rpc
        build: prod
        publish:
          image:
            tags: [php-rpc]
        promote:
          - chart: shellbox-constraints
      # Shellbox with media handling packages
      - name: media
        build: media
        publish:
          image:
            tags: [media]
      # Shellbox with Score packages
      - name: score
        build: score
        publish:
          image:
            tags: [score]
        promote:
          - chart: shellbox
      # Shellbox with SyntaxHighlight packages
      - name: syntaxhighlight
        build: syntaxhighlight
        publish:
          image:
            tags: [syntaxhighlight]
      # Shellbox with Timeline packages
      - name: timeline
        build: timeline
        publish:
          image:
            tags: [timeline]
        promote:
          - chart: shellbox-timeline
