pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
  publish:
    blubberfile: blubber.yaml
    stages:
      # Plain Shellbox with just PHP for RPC
      - name: php-rpc
        build: prod
        publish:
          image:
            tags: [php-rpc]
      # Shellbox with media handling packages
      - name: media
        build: media
        publish:
          image:
            tags: [media]
      # Shellbox with Score packages
      - name: score
        build: score
        publish:
          image:
            tags: [score]
      # Shellbox with SyntaxHighlight packages
      - name: syntaxhighlight
        build: syntaxhighlight
        publish:
          image:
            tags: [syntaxhighlight]
      # Shellbox with Timeline packages
      - name: timeline
        build: timeline
        publish:
          image:
            tags: [timeline]
      # Shellbox with audio+video handling packages
      - name: video
        build: video
        publish:
          image:
            tags: [video]
