pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: test-php73
      - name: test-php74
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: score
        build: score
        publish:
          image:
            tags: [score]
